### ISSUE TITLE
[Admin Panel] - UI - Template Cleanup and Setup Initial Config

### ISSUE THREAD

**Issue by permanar** [permanar/limosia-admin-panel#5]
## Objectives
- Remove unused files for now.
- Replaced Logo with Limosia's.
- Configure minimal setup for the menu sidebar (related to #1).
- Changed Bar Title and Favicon.
- Hide or remove the Template Customizer (floating btn on the right side).
- Changed footer copyright.

**Comment by permanar** [comment]
Sidenote:

- Change copyright year to static 2023 (since we start the project this year).
- Remove unnecessary feature icon at Header (search, messages chat box, etc).

**Comment by putradnata** [comment]
@permanar Please check PR #8

**Comment by permanar** [comment]
Thanks
